### ISSUE TITLE
windows10应用的颜色设置选择“暗”时显示异常

### ISSUE THREAD

**Issue by SongyaCAT** [PPJUST/OnlyUnzip#5]
我是用的系统是win10，颜色设置里面的应用模式选择“暗”之后，ui显示就异常了：
![image](https://github.com/PPJUST/OnlyUnzip/assets/57287191/5c2575bc-913e-4e1c-98b3-07cf3ae201f0)
![image](https://github.com/PPJUST/OnlyUnzip/assets/57287191/bdf456ff-8dac-420a-b26b-797cf0486897)
![image](https://github.com/PPJUST/OnlyUnzip/assets/57287191/d7122b2a-fdd6-48be-aaec-ddaa27a3ad02)

**Comment by PPJUST** [comment]
网盘已更新1.4.2
